# Generated by Django 4.1 on 2022-09-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='21', max_length=50, verbose_name='Title')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('fullt_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Date publication')),
            ],
        ),
    ]
